name: Anacrusis Music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12121c'
    - '#a5c7e3'
    - '#737a51'
    - '#f4d11f'
  brandStrength: 0
  lightness: 0.07473211898468435
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
